# Generated by Django 5.1.7 on 2025-05-04 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('party', models.CharField(max_length=100)),
                ('representative_field', models.CharField(max_length=100)),
                ('seat_number', models.PositiveIntegerField(unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('lawmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='lawmembers.lawmaker')),
            ],
        ),
    ]
