# Generated by Django 5.1.7 on 2025-05-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawmembers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawmaker',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lawmaker',
            name='seat_number',
            field=models.IntegerField(unique=True),
        ),
    ]
