# Generated by Django 5.1.7 on 2025-05-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0002_post_comment_predictionresult_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(blank=True, null=True)),
                ('agreement_percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetitionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='predictionresult',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='has_poll',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MonthlyKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('keyword', models.CharField(max_length=100)),
                ('score', models.FloatField()),
            ],
            options={
                'unique_together': {('month', 'keyword')},
            },
        ),
    ]
