# Generated by Django 5.1.7 on 2025-05-22 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0007_alter_vote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='user',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='petition_content',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='petition_title',
            field=models.CharField(max_length=200),
        ),
    ]
