# Generated by Django 5.1.7 on 2025-05-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0008_predictionresult_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredictionResult',
            new_name='UserPrediction',
        ),
    ]
