# Generated by Django 5.1.7 on 2025-05-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('분야', models.CharField(max_length=50, unique=True)),
                ('청원수', models.IntegerField()),
                ('색상', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='PetitionSummaryCategory',
        ),
    ]
